// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVBMplKvqMirp9lm5ZhiuCjLnHXgAG1M',
    appId: '1:639657738891:android:ab0ce0630efc3016b3ca8e',
    messagingSenderId: '639657738891',
    projectId: 'marcaa-e31c9',
    storageBucket: 'marcaa-e31c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAGLUaYR-pahBP02iDrKLKdJB8Fg4SVHY',
    appId: '1:639657738891:ios:89ddbfe5ae863651b3ca8e',
    messagingSenderId: '639657738891',
    projectId: 'marcaa-e31c9',
    storageBucket: 'marcaa-e31c9.appspot.com',
    iosClientId: '639657738891-o2hlvdfpml77rjovnsp1d7k5sidpbn4l.apps.googleusercontent.com',
    iosBundleId: 'test',
  );
}
